[package]
name = "simple_payment_service"
version = "0.1.0"
authors = ["serejkaaa512"]

[[bin]]
name = "main"
doc = false

[dependencies]
regex = "*"
rustc-serialize = "*"
hyper = "*"
rand = "*"
lazy_static = "*"


[dependencies.nickel]
version = "*"
